### ISSUE TITLE
Error handling in mountDirectory

### ISSUE THREAD

**Issue by goliatone** [goliatone/application-core#7]
Given the following scenario:
We changed to use `ascoltatori-lowfat` from previously using `ascoltatori` but we did not update the require in the module. `require` won't be able to find `ascoltatori` since is not installed anymore...

If we have an error in one of our modules, the loading cycle breaks:
```
ERROR [13:20:06] ├── core         :  true 
ERROR [13:20:06] ├── core         :  Cannot read property 'dependencies' of undefined 
ERROR [13:20:06] ├── core         :  TypeError: Cannot read property 'dependencies' of undefined
  at beans.map (/Users/guest/my-dashboard/src/node_modules/in/lib/sortByDependencies.js:146:35)
  at Array.map (native)
  at createGraph (/Users/guest/my-dashboard/src/node_modules/in/lib/sortByDependencies.js:145:11)
  at PluginLoader.sort [as sortFilter] (/Users/guest/my-dashboard/src/node_modules/in/lib/sortByDependencies.js:8:17)
  at PluginLoader.sort (/Users/guest/my-dashboard/src/node_modules/in/lib/in.js:179:21)
  at PluginLoader.load (/Users/guest/my-dashboard/src/node_modules/in/lib/in.js:150:14)
  at find.then.then (/Users/guest/my-dashboard/src/node_modules/in/lib/in.js:228:37) 
```

**Comment by goliatone** [comment]
Exiting on an error while loading a module is probably what we want. However, we probably also want better error logs, more information would be valuable. 
This is partially addressed in [in](https://github.com/goliatone/in) which is used to handle module loading.
